name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"  # runs every 12 hours
  workflow_dispatch:        # allow manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Aakashkum143
          outputs: |
            dist/snake.svg

      - name: Push Snake Animation to output branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake animation"
          add: "dist/snake.svg"
          default_author: github_actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


