name: Generate Snake

on:
  schedule: # har 12 ghante me update
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: aakashkum143
          outputs: dist/snake.svg

      - name: Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: "Generated snake animation"
          add: "dist/snake.svg"
